version: 2.1
jobs:
  build:
    shell: /bin/bash --login -eo pipefail

    macos:
      xcode: '11.5.0'

    steps:
    - checkout

    - run:
        name: Setup for builds
        command: |
          mkdir -p 'test-results'
          mkdir -p 'artifacts'

    - run:
        name: Build and test
        command: xcodebuild test -workspace 'LDEventSource.xcworkspace' -scheme 'DarklyEventSource-iOS' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max' CODE_SIGN_IDENTITY= | tee 'artifacts/xcode_raw.log' | xcpretty -r junit -o 'test-results/ios-tests/junit.xml'

    - run:
        name: CocoaPods spec lint
        command: |
          if [ "$CIRCLE_BRANCH" = 'master' ]; then
            pod spec lint
          else
            pod lib lint
          fi

    - store_test_results:
        path: test-results

    - store_artifacts:
        path: artifacts
